### ISSUE TITLE
Check if all notebook pages for riksdagsdebatterna work without errors + web link

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#128]
Från och med april ska Johan, Erik och jag börja arbeta med aktivt med riksdagsdebatterna och med de Jupyter-sidor som togs fram för detta under hösten 2020.

- Dessa Jupyter sidor behöver ses över gällande ev error som uppstår när sidorna körs.

- Vi behöver en webb-länk till Jupyter-sidorna.

**Comment by roger-mahler** [comment]
Logga in med ert Github-konto på [westac.humlab.umu.se](westac.humlab.umu.se).
Sidor för Word Trends och Co-occurrence har testats, och ser ut att fungera.

Notera att korpus aktivt måste väljas defaultvärde pekar inte på ett korrekt korpus: ärende #129
Vidare ges ibland ett icke-relevant felmeddelande, bl.a. om man glömmer att fylla i en unik tag: ärende #130
