### ISSUE TITLE
log likelihood eller tf-idf

### ISSUE THREAD

**Issue by Stubbendorff** [welfare-state-analytics/welfare_state_analytics#142]
Riksdagsdebatterna är starkt genrebundna och frekventa ord refererar ofta till debatternas form och kontext snarare än sakinnehållet: talman, utskott, replik, motion, herr, regering, riksdag. Dessa ord återkommer i tal efter tal, oberoende av det ämne man debatterar. Därför skulle vi behöva en metod för att särskilja det specifika från det allmänna – dvs: vilka ord är relativt sett mer frekventa i de sammanhang där man talar om just information, propaganda osv. Sammanhanget definieras här som ett ordfönster runt ett nyckelord och där vi vill kunna ange vilka ordklasser vi vill ta med. En sådan metod bör vara domänberoende, och alltså beräkna ordfrekvenser i specifika sammanhang relativt frekvenserna i hela korpus. Eventuellt är det mer rimligt att jämföra ordfrekvenserna för valda fönster ett specifikt år med frekvenserna i alla protokoll samma år – vilka som är de vanligaste genreorden (herr talman etc) förändras över tid. TextRank tycks inte uppfylla kraven. En metod som bygger på log likelihood eller TF-IDF är rimligare.

**Comment by roger-mahler** [comment]
Ny version tillgänglig med PPMI, TF-IDF, LLR, DICE och HAL CWR. Finns en del klarheter runt implementationen av främst LLR.
 - Möjligtvis bör fönsterstorlek tas med som parameter i formel för LLR.
 - I övrigt sker ingen explicit normalisering för LLR, HAL och DICE.
 - Vidare har prestanda för visning __väsentligt__ förbättrats.
 - För LLR finns osäkerhet om vad som ska räknas som totala antalet observationer: antalet fönster "LLR (D)" eller antalet tokens "LLR (N)". Båda har lagts in, möjligtvis påverkar det endast magnituden.
