### ISSUE TITLE
Add speech finder functionality (riksdagens_protokoll)

### ISSUE THREAD

**Issue by aibakeneko** [welfare-state-analytics/welfare_state_analytics#151]
- Separate notebook
- Callable with parameters (from other notebooks)
- Search by `text`, `person`, `topic`, etc.
- Generic with built-in filter model
- Sort order
- Preliminary result grouped by person

Example: Which person(s) and how many speeches contains `text`

**Comment by roger-mahler** [comment]
Closing this issue since similar features as requested feature have been added to notebooks.
