### ISSUE TITLE
Riksdagsprotokoll 1 – Hämta data

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#76]
Hämta hem alla riksdagsprotokoll från 1920 till 2020 i txt-format.

Protokoll från 1990 och framåt finns här: https://data.riksdagen.se/data/dokument/ – dessa ska även vara uppmärkta med metadata för vem som talar och vilket parti politikern tillhör (vilket inte är fallet med protokollen före 1990).

**Comment by roger-mahler** [comment]
A zipped file containing a text corpus of `riksdagens protokoll` has been stored in `I. Welfare State Analytics/DATA/riksdagens_protokoll/riksdagens_protokoll_1920-2020.zip`.

The data has been downloaded from KB-labb's API. The source code for the download resides in [westac_data](https://github.com/welfare-state-analytics/westac_data/tree/master/scripts/riksdagens_protokoll/step.1-compile_corpus).
