### ISSUE TITLE
Riksdagsprotokoll 3 – Jupyter ordfrekvenser

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#78]
Skapa Jupyter-sida med följande sökfunktion:

> Välja om ordsökningen ska göras på det lemmatiserade materialet eller inte
> Välja ett eller flera valfria ord
> Generera en frekvenskurvor för valda ord ord över tid (år) – möjlighet att välja total frekvens eller normaliserad frekvens
> Möjlighet att välja stapeldiagram eller trenddiagram samt att få ut frekvensdata som en cvs-fil

- [ ] Välja om ordsökningen ska göras på det lemmatiserade materialet eller inte

**Comment by roger-mahler** [comment]
Merging with #71 and closing that issue:

- [ ] Skapa en Jupyter-sida som gör det möjligt att mäta ords frekvenser över tid, baserat på de Riksdagsprotokoll som ligger uppe i KBLabs API. Vi börjar med den råa datan (senare kan det bli aktuellt att PoS-tagga materialet).
- [ ] Det ska vara möjligt att välja ett eller flera ord som man vill följa frekvensen för över tid (år).
- [ ] Det ska gå att välja att följa frekvensen som trend-graf, stapeldiagram eller en data-tabell (som man kan ladda ner som cvs-fil för vidare analys).
- [ ] Det vore också bra om det finns en funktion för se vilka protokoll som innehåller det eller de aktuella orden för ett visst år.
- [ ] Gällande frekvens över tid vore det såklart bra om man både kan se den relativa och den absoluta frekvensen

**Comment by fredrik1984** [comment]
Johan och jag skulle behöva utforska hur enskilda ord förändras över tid. Detta är därför en issue som behöver prioriteras framöver. Viktigt att man ska kunna välja om det är ett lemmatiserat eller icke-lemmatiserat ord, samt att välja om det är rå eller normaliserad frekvens (delat på totalt antal tokens ett givet år).

**Comment by roger-mahler** [comment]
Deployed to PyPI
