### ISSUE TITLE
Riksdagsprotokoll 7 – Jupyter samförekommande ord som minskar/ökar mest

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#83]
Skapa en Jupyter-sida med funktion för att följa vilka samförekommande ord som minskar/ökar mest under en tidsperiod. Denna issue baserar sig på funktionaliteten från issue Riksdagsprotokoll 6. Därtill kan man förmodligen även återanvända funktionaliteter från arbetet med klustring av ordfrekvenser över tid.

- Skapa funktion som gör att man kan få en lista på de samförekommande ord till ett visst nyckelord (t ex "information") som minskar/ökar mest under en vald tidsperiod (forskaren väljer själv om det ska vara en lista med ord som ökar eller minskar). 
- För att undvika ord med låg samförekomstfrekvens ska man kunna välja ett tröskelvärde (låt säga att ett ord ska samförekomma minst 100 gånger totalt under tidsperioden) och endast fokusera på de ord över detta värde som ökar/minskar mest över tid
- Denna lista med samförekommande ord som minskar/ökar över ska kunna visualiseras som ett stapel- eller trenddiagram. Dvs om "dålig" är ett samförekommande ord till "information" som minskar mycket under perioden ska detta ords samförekomstfrekvens följas över tid
- Även till denna funktion antar jag att det bör finnas ett normaliserande mått på toppordens samförekomstfrekvens

**Comment by roger-mahler** [comment]
Deployed to PiPY,  use #104 to install new version.

**Comment by fredrik1984** [comment]
Denna issue är ju inte färdig – i alla fall inte så som Johan och jag tänkts oss den! Men jag ser att jag inte heller var helt tydlig när jag skrev issuen från början.

Det vi också vill få ut liknar det vi gjorde med klustringen av ordtrender i SOU-materialet. Men här vill vi istället klustra vilka enskilda collocates-ord som har liknande frekvens över tid. 

Alltså vore det lämpligt att implementera en hierarkisk klustringsmodell på det collocates som genereras av modellen. Om nyckelordet är "information" ska vi kunna följa hur enskilda collocates till nyckelordet (information-livsmedel, information-problem, information-barn) klustras samman och inte hur collocates-par till nyckelordet (livsmedel-kött, problem-möjlighet, barn-förälder) klustras samman.

**Comment by roger-mahler** [comment]
Ok, inte lätt at läsa ut en sådan kravbild av ärendet.  Jag lägger upp det som ett nytt ärende och stänger detta.

**Comment by fredrik1984** [comment]
> Ok, inte lätt at läsa ut en sådan kravbild av ärendet. Jag lägger upp det som ett nytt ärende och stänger detta.

Fråga: är det möjligt att få till den funktionaliteten till nästa vecka?
